workflows:
  my-workflow:
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
      cancel_previous_builds: true
    publishing:
      email:
        recipients:
          - mgierschdev@gmail.com
