workflows:
  run-on-push-hook:
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
      cancel_previous_builds: true

publishing:
  email:
    recipients:
      - mgierschdev@gmail.com
    notify:
      success: true
      failure: true
