pipeline {
    agent { 
        node {
            label "master"
            customWorkspace "/Users/macbookpro/work/Repositories/Jenkins/"
        }
    }
    env.BUILD_NUMBER
    environment {
        UNITY_PATH = "/Applications/Unity/Hub/Editor/2022.1.16f1/Unity.app/Contents/MacOS/Unity"
    }
    
    stages {
        stage('Test EditTests') {
            steps {
                echo 'EditTests..'
            }
        } 

       stage('Test PlayModeTests') {
            steps {
                echo 'PlayModeTests..'
            }
        }
        stage('Build IOS') {
            steps { 

                echo 'Bulding....'
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
                sh "${UNITY_PATH} -quit -batchmode -projectPath IOS/${env.BUILD_ID}/ -executeMethod  BuildScript.PerformIOSBuild -stackTraceLogType Full --silent-crashes"
                        
                //  bat "\"${UNITY_PATH}\" -batchmode -projectPath . -executeMethod BuildScript.PerformBuild -logFile build.log"
                // /Applications/Unity/Hub/Editor/2021.3.5f1/Unity.app/Contents/MacOS/Unity -projectPath '/Users/macbookpro/work/Repositories/TestUnityProject' -executeMethod BuildScript.PerformBuild -logFile 'build.log' 
            }
        }
        
        stage('Build Android') {
            steps { 
                echo 'Bulding....'
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
                sh "${UNITY_PATH} -quit -batchmode -projectPath Android/${env.BUILD_ID}/ -executeMethod  BuildScript.PerformAndroidBuild -stackTraceLogType Full --silent-crashes"
                        
                //  bat "\"${UNITY_PATH}\" -batchmode -projectPath . -executeMethod BuildScript.PerformBuild -logFile build.log"
                // /Applications/Unity/Hub/Editor/2021.3.5f1/Unity.app/Contents/MacOS/Unity -projectPath '/Users/macbookpro/work/Repositories/TestUnityProject' -executeMethod BuildScript.PerformBuild -logFile 'build.log' 
            }
        }
    }                       
}